# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Code Quality
        run: |
          echo Shared Lint
          echo Tests Lint
          echo Apis Lint
          echo Apps Lint
        
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: |
          echo Apis Unit Tests
          echo Apps Unit Tests
          echo Shared Unit Tests
          
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        run: |
          echo Apis Coverage
          echo Apps Coverage
          echo Shared Coverage          
          
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo Build Apis
          echo Build Beheer
          echo Build CMS
          echo Build Mob Grammar
          echo Build Mob Grooveme
          echo Build Mob Spelling
          echo Build PO Leerkracht
          echo Build PO Student
          echo Build VO Docent
          echo Build VO Leerling
          echo Build Readiant Player
          
  build-external:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build External
        run: |
          echo Build Bestelhulp
          echo Build Smart Life
          
  build-interal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Interal
        run: |
          echo Build Package Monitor
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo Apis Unit Tests
          
