name: Deploy Production Stage

on:
  workflow_run:
    workflows: [Building Stage]
    branches: [main]
    types:
      - completed
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo Apis Unit Tests
          
