name: Merge to Master

on:
  push:
    branches: [master]

jobs:
  test:
    name: Testing Stage
    uses: marc0tjevp/jobs-test/.github/workflows/stages/test.yml@master

  build:
    name: Building Stage
    needs: test
    uses: marc0tjevp/jobs-test/.github/workflows/stages/build.yml@master

  deploy:
    name: Deploy to production
    needs: [test, build]