name: Pull Request to Master

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Testing Stage
    steps:
      - uses: marc0tjevp/jobs-test/.github/workflows/test.yml@master

  build:
    name: Building Stage
    needs: test
    steps:
        - uses: marc0tjevp/jobs-test/.github/workflows/build.yml@master
