# Steps for testing
name: Testing Stage

on:
  workflow_call:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Code Quality
        run: |
          echo Shared Lint
          echo Tests Lint
          echo Apis Lint
          echo Apps Lint

  unit-test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Unit Tests
        run: |
          yarn -v
          npm -v
          node -v
          echo Apis Unit Tests
          echo Apps Unit Tests
          echo Shared Unit Tests

  coverage:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Coverage
        run: |
          echo Apis Coverage
          echo Apps Coverage
          echo Shared Coverage
