name: Testing Stage

on:
  workflow_call:

jobs:
  code-quality:
    name: Code Quality
    uses: marc0tjevp/jobs-test/.github/workflows/test-cq.yml@master

  unit-test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: |
          echo Apis Unit Tests
          echo Apps Unit Tests
          echo Shared Unit Tests

  coverage:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        run: |
          echo Apis Coverage
          echo Apps Coverage
          echo Shared Coverage
